apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nest-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  backend:
    serviceName: nest-app-service
    servicePort: 80