apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nest-app-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nest-app-prod
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60